// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultConfig(arg1) {
  return window['go']['main']['App']['DefaultConfig'](arg1);
}

export function InputMethods() {
  return window['go']['main']['App']['InputMethods']();
}

export function MethodRequirement(arg1) {
  return window['go']['main']['App']['MethodRequirement'](arg1);
}

export function OpenWebInput() {
  return window['go']['main']['App']['OpenWebInput']();
}

export function Start(arg1) {
  return window['go']['main']['App']['Start'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
