// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {inputmethod} from '../models';
import {main} from '../models';
import {runner} from '../models';

export function DefaultConfig(arg1:string):Promise<inputmethod.Config>;

export function GetLogs():Promise<Array<string>>;

export function InputMethods():Promise<Array<inputmethod.Info>>;

export function MethodRequirement(arg1:string):Promise<main.MethodRequirement>;

export function OpenWebInput():Promise<void>;

export function Start(arg1:inputmethod.Config):Promise<runner.Status>;

export function Status():Promise<runner.Status>;

export function Stop():Promise<runner.Status>;
